import Head from "next/head";
import Navbar from "../../padroes/Navbar";

function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Navbar />

			<main>
				<h1>
					Home Page
				</h1>
			</main>

			<footer>
				Rodape
			</footer></>
	);
}

export default Home;